#!/usr/bin/env bash

commit_msg_file="$1"
commit_msg=$(head -n1 "$commit_msg_file")

# Conventional commit regex
pattern="^(breaking changes|feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9_-]+\))?: .+"

if [[ ! $commit_msg =~ $pattern ]]; then
  echo "❌ Commit message does not follow Conventional Commits!"
  echo ""
  echo "Examples:"
  echo "  feat: add host info endpoint"
  echo "  fix(server): panic on nil pointer"
  echo "  docs: update README"
  echo "  chore: bump dependencies"
  echo ""
  echo "Your commit message:"
  echo "  $commit_msg"
  echo ""
  exit 1
fi

echo "✔ Commit message format OK."
